using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Complete
{
    public class CameraMovement : MonoBehaviour
    {
        public Stats stats;
       // public float m_DampTime = 0.2f;                 // Approximate time for the camera to refocus.
        //public float m_ScreenEdgeBuffer = 4f;           // Space between the top/bottom most target and the screen edge.
       // public float m_MinSize = 6.5f;                  // The smallest orthographic size the camera can be.
        public Transform mainCharacterRef;
        [HideInInspector] public Transform[] m_Targets; // All the targets the camera needs to encompass.


        private Camera m_Camera;                        // Used for referencing the camera.
        private float m_ZoomSpeed;                      // Reference speed for the smooth damping of the orthographic size.
        private Vector3 m_MoveVelocity;                 // Reference velocity for the smooth damping of the position.
        private Vector3 m_DesiredPosition;              // The position the camera is moving towards.


        private void Awake()
        {
            m_Camera = GetComponentInChildren<Camera>();
        }


        private void FixedUpdate()
        {
            // Move the camera towards a desired position.
            Move();

        }


        private void Move()
        {
            // Find the average position of the targets.
            FindAveragePosition();

            // Smoothly transition to that position.
            transform.position = Vector3.SmoothDamp(transform.position, m_DesiredPosition, ref m_MoveVelocity, stats.cameraDampTime);
        }


        private void FindAveragePosition()
        {
            Vector3 averagePos = new Vector3();
            int numTargets = 0;

            if (mainCharacterRef != null)
            {
                averagePos = mainCharacterRef.transform.position;
                numTargets = 1;
            }

               

            // Go through all the targets and add their positions together.
            for (int i = 0; i < m_Targets.Length; i++)
            {
                // If the target isn't active, go on to the next one.
                if (!m_Targets[i].gameObject.activeSelf)
                    continue;

                // Add to the average and increment the number of targets in the average.
                averagePos += m_Targets[i].position;
                numTargets++;
            }

            // If there are targets divide the sum of the positions by the number of them to find the average.
            if (numTargets > 0)
                averagePos /= numTargets;

            // Keep the same y value.
            averagePos.y = mainCharacterRef.transform.position.y;//transform.position.y;

            // The desired position is the average position;
            m_DesiredPosition = averagePos;
        }
    }
}